package com.closer.prophet.filter;

import java.io.Serializable;

public class BrowsingHistoryFilter implements AbstractFilter, Serializable {
    @Override
    public boolean filter(String log) {
        boolean result = false;

        if(org.apache.commons.lang3.StringUtils.isBlank(log)) {
            return false;
        }

        while(log.contains(" :")) {
            log = log.replace(" :", ":");
        }

        // log without field "udid" are not generated by human behavior.
        // for example, visiting API by postman will generate log without udid.
        if (log.toLowerCase().contains("\"x_closer_udid\":")) {
            result = true;
        }

        return result;
    }
}
